### ISSUE TITLE
[Suggestion]: make 'commend a player' a round end popup or button next to 'OOC'

### ISSUE THREAD

**Issue by WoodenTucker** [Darkrp-community/OpenKeep#100]
### Category

Other

### What is the suggestion?

yeah anyway whenever the round ends you have about 15 seconds to try and click commend while people are spamming the (text limited) chatbox, if you dont click it, too bad, there's not a way to get it to pop up again

therefor we should make 'commend a player' a popup or add it next to the OOC button during round 

### Why is this suggestion good?

it would make commends easier and more common

**Comment by WoodenTucker** [comment]
good execution of this would be on TG station where it pops up asking if you want to +1 a player

**Comment by BlueMemesauce** [comment]
dont you dare steal my pr !!!!!

**Comment by Wesreidau** [comment]
Please do this, its on Blackstone and can't be that hard to find.
