### ISSUE TITLE
[Bug]: Queen's cloak is the incorrect color when not holding an item in the left hand

### ISSUE THREAD

**Issue by immortalartisan** [Darkrp-community/OpenKeep#1001]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

Dun Manor

### Describe the issue

![Screenshot 2024-10-21 222159](https://github.com/user-attachments/assets/4215c5cc-0b36-49fa-b5b7-e528b037790b)
Cloak is incorrect color when not holding item in left side
![Screenshot 2024-10-21 222152](https://github.com/user-attachments/assets/fd5ffc91-c210-4d05-aa7c-f97d1ee47366)
Magically becomes the correct color when holding item and changing sprite 

### How to reproduce

1. Be an human female
2. Select queen role without king
3. Select colors as purple followed by black
4. Don't hold an item in left hand

### Round ID

Sherwood1223-04.24.48

**Comment by NPC1314** [comment]
Can anyone replicate this? I cant

**Comment by NPC1314** [comment]
Can´t replicate so no fix is likely to come any time soon. Should it return, please make a new issue.
