### ISSUE TITLE
[Bug]: Vampire Lords can make armor for free without costing Vitae

### ISSUE THREAD

**Issue by casualspacestation14enjoyer** [Darkrp-community/OpenKeep#103]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

RogueTown

### Describe the issue

![image](https://github.com/Darkrp-community/OpenKeep/assets/111151681/df76316d-219b-4b50-879c-3274c8c11345)
the code shows the issue well i believe

### How to reproduce

1. press forge armor
2. walk away
3. armor is made without costing vitae

**Comment by ThePainkiller** [comment]
Closing as completed by #196
