### ISSUE TITLE
[Bug]: Archvist's Robe Sprite inconsistency

### ISSUE THREAD

**Issue by Yakunan** [Darkrp-community/OpenKeep#1040]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

Dun Manor

### Describe the issue

On the side view the Archivists robe is missing the sleeves.
![Screenshot 2024-10-31 090021](https://github.com/user-attachments/assets/e8ab453a-2135-42c8-a201-5615fd780233)
![Screenshot 2024-10-31 090026](https://github.com/user-attachments/assets/b1638d9a-f1bb-43a6-b6e1-5cafb431931b)
![Screenshot 2024-10-31 090050](https://github.com/user-attachments/assets/120f279d-d601-444e-8cd8-f723d2d8b5b2)

### How to reproduce

Get archivists robe
Don the Robe
Turn East or West

**Comment by lavillastrangiato** [comment]
it's because you're a dwarf and i didn't make the sleeves for dwarves yet :3

**Comment by Yakunan** [comment]
It's a Humen. The same issues appears with the Formal silks. Maybe it's something else than just the clothing sprites?
![Screenshot 2024-10-31 091230](https://github.com/user-attachments/assets/7046d81b-122b-4d03-b78a-0737f88f450e)
![Screenshot 2024-10-31 091234](https://github.com/user-attachments/assets/a22849b3-0f1e-414e-8ddb-fffaeb8e95e1)

Could be just the sprites or maybe something else.

**Comment by cornercube** [comment]
> Could be just the sprites or maybe something else.

#1042 will fix the formal silks
