### ISSUE TITLE
[Suggestion]: Archivist Appartment, wall misplacement.

### ISSUE THREAD

**Issue by Yakunan** [Darkrp-community/OpenKeep#1041]
### Category

Map change

### What is the suggestion?

Could someone remove the Wall so this entrance is actually useable. I like secret entrances but this secret entrance is too secret and i don't know how to go past it.

![Screenshot 2024-10-31 110800](https://github.com/user-attachments/assets/d420ada0-d8bd-4edd-aad5-4ec9e72ea1d3)

### Why is this suggestion good?

Makes door actually useable.

**Comment by NPC1314** [comment]
Probably fixed
