### ISSUE TITLE
[Suggestion]: fix treasuries passive income 

### ISSUE THREAD

**Issue by Wateronix** [Darkrp-community/OpenKeep#106]
### Category

Balance

### What is the suggestion?

**The Issue:**
Currently you can put any item into the vault and have it generate interest at quite ridiculus rates, without code diving i think it is somewhere arround 20-ish percent. As the treasury is also filled with a lot of money roundstart, you can have infinite money, very quickly.

**Possible Solutions:**

- just revert the treasury change, though that would be boring.
- remove the starting treasury, lower the income to a more reasonable ammount (perhaps a total of 20% per day)
- make it so only some select items grant the interest.

### Why is this suggestion good?

Free money, without having to do anything, is not really interesting.

**Comment by Wesreidau** [comment]
I would agree it can cap obscenely high, but it also provides the king the sort of passive tax income he needs to pay guards and so forth. Also the vault is a poorly-patrolled target for thief roleplay, and if there is no wealth in in it or reason to fill it with wealth, it will be wasted roleplay potential.

**Comment by ThePainkiller** [comment]
Economy and vault rebalance currently being worked on

**Comment by InsightfulParasite** [comment]
https://github.com/Darkrp-community/OpenKeep/pull/300 Some notes that may help in understanding the issue. The treasury takes 25% of the sellprice of items. So if you have 4 100 sellprice items you will get (25*4)/queens tax which is randomized on intilization. Initialization queens tax ranges from 9% to 30% meaning at best you will get 90 mammon from the 4 100 items but at worst you get 70 mammon.

**Comment by InsightfulParasite** [comment]
It is a strange system since it is a investment mechanic. If the town cannot survive on its own commerce by selling copious amounts of apples and buying several pounds of iron you can invest and become disconnected from the town.

**Comment by Wesreidau** [comment]
All right, after thinking about this with some Merchant rounds as opposed to Hand rounds I've got some thoughts.

1. The current system accepts coins at face value for purposes of being interest-bearing treasure.
2. There is a very simple loop of turning treasury to coins and throwing coins in the vault to get more principle for the interest.
3. The loop to turn money to treasure is far more complicated with imports, exports, player interaction, haggling, conversation... so nobody does it.

If we remove 1 and 2 from the formula, that is, check if an object is a coin and if so, don't consider it a vault treasure, suddenly the steward is engaged in 3: buying resources and having others turn it into treasure or other valuables, then moving these large bulky objects into the keep.

That fixes the vault being a money printer.

I'd like to tackle this, actually.

**Comment by Technobug14** [comment]
That's great and all except play Steward and try to get players to provide treasures or other valuables. You'll bawl your eyes out and the King will be pissed that the Kingdom is broke. Maybe you'll have more success if you play a female Steward who'll spread her legs for gold ingots and gemeralds. Even if you manage to find someone willing to sell you these things, good luck buying them with no mammons in the treasury from paying the guards and such.

**Comment by NanakoAC** [comment]
Perhaps more focus on collecting taxes from other players would be interesting. Since such a thing promotes interaction, and potential conflict, between players
