### ISSUE TITLE
[Bug]: Psysicker's robe is not visible on a female dwarf

### ISSUE THREAD

**Issue by Klein3** [Darkrp-community/OpenKeep#1064]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

Dun Manor

### Describe the issue

The psysicker's robe is not visible on dwarven females.
![dwarfnorobe](https://github.com/user-attachments/assets/1921143e-d2b0-436a-992f-e6089b3cbb8d)

**Comment by NPC1314** [comment]
Fixed
