### ISSUE TITLE
[Suggestion]: Remove female tabard restrictions.

### ISSUE THREAD

**Issue by NunLeft** [Darkrp-community/OpenKeep#107]
### Category

Other

### What is the suggestion?

Females can currently only wear WHITE, YELLOW, and RED tabards. Any other design, coloration, etc is auto defaulted to one of the three for some reason.

### Why is this suggestion good?

You can't make new tabards for female guards, you can't represent your employer as a mercenary, you can't have tabard drip... Fucked up.

**Comment by BadAtThisGame302** [comment]
I believe this was fixed.
