### ISSUE TITLE
[Bug]: Orcs/goblins aren't regenerating their stamina when occupied by a mind [usually through adminbus]

### ISSUE THREAD

**Issue by 1N7Slayer** [Darkrp-community/OpenKeep#1077]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

Dun Manor, DakkaTown

### Describe the issue

I occupied an orc and spawned another orc and did my best to deplete my stamina as best as possible. While my green gauge went down, it did not go back up over time, eventually causing me to be perpetually stamlocked and unable to output any damage.

**Comment by NPC1314** [comment]
Question is if https://github.com/Darkrp-community/OpenKeep/pull/1055 changed how the NPC behave when not minded?
Its possible the norogfatstamrogfat only affeects player mobs.
Some gobbo dueling is in order.

**Comment by lavillastrangiato** [comment]
why are you assigning this to me what makes you think i know how to fix it
