### ISSUE TITLE
[Bug]: Devotion cost of miracles not always working

### ISSUE THREAD

**Issue by NPC1314** [Darkrp-community/OpenKeep#1092]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

Dun Manor

### Describe the issue

Previously paladins using churn could go plus in devotion and bypass class limit to get all spells for that patron
Latest report 
![devotionbugpng](https://github.com/user-attachments/assets/58502b97-c783-4866-b63f-55a008f97a74)
cleric using minor miracle, cost not applied.

Possibly general issue of spell not calling  parent proc cast()

**Comment by TheMrBakit** [comment]
Blessing crops cost devotions but healing doesn't. just letting you know

**Comment by ThePainkiller** [comment]
> Blessing crops cost devotions but healing doesn't. just letting you know

THANK YOU SO MUCH FOR THE TIP, I'm racking my brain trying to fix this and no matter what I do it's just not deducting devotion, but this might help!

**Comment by ThePainkiller** [comment]
![imagen](https://github.com/user-attachments/assets/0798d945-0ca2-4b4b-8458-47a6055b2df4)

Yep, just a simple and proper call to parent on cast() and all is solved.
