### ISSUE TITLE
[Bug]: No sex?

### ISSUE THREAD

**Issue by Zombuzi** [Darkrp-community/OpenKeep#115]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

RogueTown

### Describe the issue

Can't do anything about my lovefiend. Can't remove my own or other's underwear for great high quality dark fantasy RP.

### How to reproduce

Try to remove underwear.

### Round ID

Halberd64-03.54.52

### Staff ckey

N/A

**Comment by BadAtThisGame302** [comment]
Have you tried middle mouse button while targeting your groin?

**Comment by Zombuzi** [comment]
> Have you tried middle mouse button while targeting your groin?

Yes. No works. Strange.
