### ISSUE TITLE
[Bug]: Rounds start automatically without anyone readied up.

### ISSUE THREAD

**Issue by AudiGzz** [Darkrp-community/OpenKeep#1164]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

Dun Manor

### Describe the issue

erm..... rounds can start automatically without anyone readied up currently. I believe it should require a court role to start or whatever I'm not too sure but yeah. also just making this issue so a litter of cats dont get drowned in a bath tub.

### How to reproduce

erm... just wait and ponder as the round starts automatically.

**Comment by AudiGzz** [comment]
https://github.com/Darkrp-community/OpenKeep/pull/1129 probably and most likely related to this pr.

**Comment by lavillastrangiato** [comment]
Can be closed.

**Comment by AudiGzz** [comment]
im CLOOOOSSSSSSSSSSSSSSSSSINGGGGGGGGGGGG AUUUUUUUUUUUGHHHHHHHHHHHHHHHHHHHHHHHHHHHH
