### ISSUE TITLE
[Suggestion]: Alcohol Distillation and Expansion System

### ISSUE THREAD

**Issue by JohnnyJohnJohnson** [Darkrp-community/OpenKeep#142]
### Category

New Role, Other

### What is the suggestion?

It would be cool if we could make distilleries to turn basic alcohol into more concentrated types. A still should take maybe one or two cogs and a steel ingot to craft, and use...  I'm actually not sure what crafting skill it should need. Barely anybody gets engineering so that doesn't seem feasible, discuss in the comments. The Farm should start with a still somewhere in it already, or the Brewery if one is added to the map.

Distilled alcohol should give you the "drowned sorrows" moodlet, giving you increased peace for a longer period of time than the "drunk" moodlet. Once the moodlet expires the player should gain the "hangover" moodlet, giving them some stress, lowering perception and endurance by 1, and immediately progressing them by one thirst level. The hangover moodlet and all of it's effects expire immediately after the player drinks some water (or more alcohol).

The types of alcohol I've thought of so far, based on what we have:
Beer -> Whiskey
Ale -> Stout
Wine -> Brandy
Cider -> Calvado

Potential alcohol types thought of for potential future crops.
Maize: Barrel -> Chicha, Distillation -> Bourbon
Potato: Barrel -> Potato Juice (does not get you drunk, just makes you vomit), Distillation -> Vodka
Sugar (from cane, beets, or whatever other crop is added that makes sugar): Barrel -> Grog, Distillation -> Rum
Honey: Barrel -> Mead, Distillation -> Goldwine

Since filling a 300 unit barrel takes a VERY long time and a HUGE amount of plants, I had the idea of adding kegs.
Kegs are crafted two at a time with one log and two sticks. A keg can hold 100 units of liquid, but it cannot be drunk from without a cup or something else to take the liquid from it. A keg can be carried by hand, but it requires both hands to lift like a large log or dwarven music box. Multiple kegs can also fit into a handcart. You can fill and feed kegs into and from barrels like buckets.

Alcohol should be worth something when exported by the Merchant, seeing as the Guild can import it now. Distilled alcohol should be worth more. Also, we should be able to empty sacks into barrels so we don't have to drop things in one at a time.
![Stonekeep Fluid Storage 101](https://github.com/Darkrp-community/OpenKeep/assets/126877934/ef539c53-598a-48a1-baf5-ca2d46ed7ce9)

### Why is this suggestion good?

Expands the domestic and towner roles and adds opportunities for brewer RP and RP involving more refined alcohol. It allows someone to make a living off buying alcohol ingredients and selling the booze, to local sources and to the Merchant's Guild. It also makes actually selling alcohol easier with the inclusion of kegs that can be carried around.

**Comment by NPC1314** [comment]
Hi, thanks for your suggestion! Unfortunately it's not feasible for us to prioritise this feature right now, but we'll keep it in mind and we'll hopefully revisit it in the future. To keep the issues page relevant we have to close suggestion nobody is working on after a while.
