### ISSUE TITLE
[Suggestion]: Randomly Generated Decoration objects outside town

### ISSUE THREAD

**Issue by Metrobotic** [Darkrp-community/OpenKeep#172]
### Category

Alteration to the world/setting

### What is the suggestion?

Add decoration into Murderwood and Mount Decap to match their namesake. Provide hanging bodies or gibbeted bodies for Murderwood and head-on spikes or skeletonized bodies in Mount Decap. These would not be static and could be random generated to make the place more lived in. head-onMount Decap

### Why is this suggestion good?

Because it'll make the areas outside of town less mundane and provide a livelier setting in the world, it's called Murderwood and Mount Decap, so why are there no heads on Mount Decap or the lack of bodies/blood in Murderwood? Give these places a more sense of dread outside of simply the active dangers of the wildlife and hostile entities.

**Comment by ThePainkiller** [comment]
IF ONLY FUCKING MAPGEN WORKED, THIS WAS A THING BEFORE PRE-PUBLIC REPO AAAAAAAAAAAAGH I'M GOING INSANE

**Comment by Purvm** [comment]
Hello.
A suggestion to your suggestion, or rather an expasion to it.
Perhaps, bodies hanging from the trees could be cut down (or the tree itself, rather) and looted, perhaps, with randomized loot.
I think heads on spikes would fit better in the swamps. And old battlefields, maybe with deadites as they weren't properly given the Maiden's rest.
If mapgen is fixed, whatever that means, and we can have randomized spots. Ambushed caravans, abandoned encampments, and such, could be a nice addition.
Giving the treasure hunter and gravediggers more of a reason to exist would be cool, they ignore common tabboos and sins in search of riches left by less fortunate man, but I think for that to be fully implemented, perhaps in the future, crypts would have to be added.
I wish I could code for shit without chatGPT for me to assist way more than simply suggesting.
