### ISSUE TITLE
[Bug]: Hitting Church bell with Bell knocker does not announce it.

### ISSUE THREAD

**Issue by Teragenic** [Darkrp-community/OpenKeep#173]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

RogueTown

### Describe the issue

Using the Bell Knocker(Mace) on the church belltower does not announce it to the world, unlike using the bell 'remote'(Bell).

### How to reproduce

Use the Bell Knocker on the church belltower.

### Round ID

N/A

### Staff ckey

N/A

**Comment by Teragenic** [comment]
Handheld bell. The one that spawns works, it's the manual hitting of the bell with the bell knocker that doesn't work.. If you attack the bell, you attack it. Nothing happens.

**Comment by ThePainkiller** [comment]
![image](https://github.com/Darkrp-community/OpenKeep/assets/1294508/ba1d340c-e192-4a68-8821-4a8488ea9267)

After localtesting, it plays the sound, and even displays the text. What you meant is that it doesn't do both these things **GLOBALLY.**

**Comment by ThePainkiller** [comment]
Closed as completed by #189 .
