### ISSUE TITLE
[Bug:] It rains still in roofed areas. 

### ISSUE THREAD

**Issue by Teragenic** [Darkrp-community/OpenKeep#174]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

RogueTown, RogueWorld

### Describe the issue

It rains under structures

### How to reproduce

Rain

### Round ID

N/A

**Comment by NPC1314** [comment]
Its due to some map PR issues likely, being worked on

**Comment by NPC1314** [comment]
Finally this dragon has been slain by Crown Prince
