### ISSUE TITLE
[Bug]: ROUS Attack Each Other!

### ISSUE THREAD

**Issue by DAKKA-WAAAGH** [Darkrp-community/OpenKeep#180]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

RogueTown

### Describe the issue

While I'm testing my maps, I'm seeing the Rous attack each other in the terminal... no wonder I wasn't ever seeing the correct amount of Rous.

It would be more interesting if they banded together instead, and continued to spread if ignored.

### How to reproduce

Place two Rous in a room, they WILL kill each other.

### Round ID

N/A

### Staff ckey

N/A

**Comment by NPC1314** [comment]
also /smallrats eats each other, needs blacklisting itself in food

**Comment by ThePainkiller** [comment]
Closing as completed by #195
