### ISSUE TITLE
[Bug]: Admins can't Get Mob someone wearing a helmet that obscures their identity, such as a bucket helm!

### ISSUE THREAD

**Issue by DAKKA-WAAAGH** [Darkrp-community/OpenKeep#182]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

RogueTown

### Describe the issue

While testing my map, I use Get Mob to get around quicker. Decided to test as a Crusader, whom starts with a bucket helmet, and had it equipped for fun. When I tried to Get Mob my character, it didn't teleport him. I took the helmet off, checked the name and was 100% sure it was the right mob I was trying to get. Then I aghosted and Get Mob'd again and, sure enough, it worked.

Repeated the process both with the helmet on and off and found that the helmet on made me un-Getable.

### How to reproduce

1. Put obscuring helmet on
2. Get Mob
3. Be confounded

### Round ID

N/A

### Staff ckey

N/A

**Comment by NPC1314** [comment]
Is this a problem in the live server too? Any admin can confirm?

**Comment by NPC1314** [comment]
can't be replicated on live server
