### ISSUE TITLE
[Suggestion]: Make it a little easier for butlers/maids to supply the manor with food

### ISSUE THREAD

**Issue by Optimism333** [Darkrp-community/OpenKeep#231]
### Category

Balance

### What is the suggestion?

Feeding the manor is very difficult for the manor servants if there's no soilsons, and is one of the main functions of the butlers/maids present in the manor (besides pouring wine and looking pretty). I have two suggestions for how this burden might be reduced.

## Suggestion 1: ##
- The first suggestion is to give maids and butlers at least weak/average farming skill and a tiny gardening space (even as small as 3x2 tiles) at the manor. This would at least allow them to supply at least a few people at the manor with food, while still having to go to the farm for additional grain, meat, and milk if they want to make more complex dishes or supply a feast. 

- To not make soilsons lose relevance, the garden should start with just a few seeds and also lack tools besides a sickle and a hoe.

## Suggestion 2: ##
- The second suggestion is to add more supplies to the manor kitchen on round start. According to a player, currently only three pieces of grain spawn at the manor, along with a stick of butter, a steak, and three eggs. My suggestion would be to double the amount of grain and add some more meat, or a chest with some fresh fruit. Enough to last for a few meals before a run to the farm becomes necessary just to keep the royal family fed.

### Why is this suggestion good?

- Slightly eases the burden on butlers/maids of keeping the royal family fed, either by giving them a small amount of production potential, or adding some more ingredients to the manor kitchen for them to use.

### Staff consulted

N/A

**Comment by NPC1314** [comment]
Probably best to bump up the stores a little for Keep first to see if it helps before expanding servants roles too much. Adding it to the map cleanup list.
