### ISSUE TITLE
[Bug]: Treasure Hunter has no armor proficency

### ISSUE THREAD

**Issue by OctusGit** [Darkrp-community/OpenKeep#274]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

RogueTown

### Describe the issue

treasure hunter spawns with a haubergeon, but is not proficient in it, making it an issue when worn or doing things with it equipped

### How to reproduce

spawn as treasure hunter, get the haubergeon, attempt to jump and realize you have no proficiency in the armor type

### Round ID

Castle301-21.00.50

**Comment by ThePainkiller** [comment]
Will be left obsolete by future PR, they will get leather armor
