### ISSUE TITLE
[Suggestion]: Make the Jesters hat/tunick color customizable, similarly to the tabard.

### ISSUE THREAD

**Issue by sanshoom** [Darkrp-community/OpenKeep#287]
### Category

Other

### What is the suggestion?

I just want to have unique colors for jesters rather than the same old one that's been used since.. forever.

### Why is this suggestion good?

Instead of having someone make an /entirely/ new outfit, we could just make the tunick color customizable so people can make their jesters actually look unique and different from one another.

**Comment by NPC1314** [comment]
Hi, thanks for your suggestion! Unfortunately it's not feasible for us to prioritise this feature right now, but we'll keep it in mind and we'll hopefully revisit it in the future. To keep the issues page relevant we have to close suggestion nobody is working on after a while.
