### ISSUE TITLE
[Bug]: Elf Huntress Can No Longer Write On Custom Signs

### ISSUE THREAD

**Issue by Optimism333** [Darkrp-community/OpenKeep#292]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

As recently as maybe a week ago, two at most, I was able to carve some words into a custom sign while playing elf huntress.

I used this to "claim" a house in town, or leave signs with instructions for people. However, this changed recently. I am no longer able to carve words into signs, I just get the message "I don't know any verba."

I'm not sure if elves used to get minor reading skill and that was removed, or if something else caused this.

I know it still worked for a while after the cooking module update was being test merged, to provide a vague timeline.

### How to reproduce
- Play elf huntress
- Try to carve words into a custom sign using stab intent with a hunting knife
- "I don't know any verba."

### Round ID

N/A

### Staff ckey

N/A

**Comment by ThePainkiller** [comment]
How long ago was the last time you could do this? I don't recall hunters getting reading skill, which might be what's missing to do this...

**Comment by Optimism333** [comment]
> How long ago was the last time you could do this? I don't recall hunters getting reading skill, which might be what's missing to do this...

About a week or two ago at most. I found exactly why as well:
![image](https://github.com/Darkrp-community/OpenKeep/assets/81007356/8e567da4-c0bd-4fb0-868e-d1fb52300f93)

Elves used to get a weak boost to their reading skill, little flavor bit (perhaps because they're long-lived or because of higher intelligence as opposed to strength).

At some point, this was either removed from the code, or stopped working. It wasn't too long ago, either.

**Comment by ThePainkiller** [comment]
Is this still a thing that happens or was it bugged that one time? Our race checks changed in between this bug report and now.

**Comment by BadAtThisGame302** [comment]
This was fixed.
