### ISSUE TITLE
[Bug]: Noc Acolytes can remain invisible forever.

### ISSUE THREAD

**Issue by sanshoom** [Darkrp-community/OpenKeep#306]
### Checks

- [x] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

DakkaTown

### Describe the issue

Once you cast invisibility onto yourself as an acolyte of Noc, you cannot leave the invisibility state.

### How to reproduce

Cast invisibility onto yourself.

### Round ID

Tapir329-17.22.03

**Comment by BadAtThisGame302** [comment]
This was fixed.
