### ISSUE TITLE
[Suggestion]: Give the gavel a proper sound

### ISSUE THREAD

**Issue by Piston1937** [Darkrp-community/OpenKeep#331]
### Category

Alteration to the world/setting, Other

### What is the suggestion?

As of right now.  The gavel makes a pitiful sound.  We need a proper slaming gavel sound.

### Why is this suggestion good?

Because SILENCE IN THE COURTROOM has a lot more weight when you have a proper slam.

**Comment by NPC1314** [comment]
Hi, thanks for your suggestion! Unfortunately it's not feasible for us to prioritise this feature right now, but we'll keep it in mind and we'll hopefully revisit it in the future. To keep the issues page relevant we have to close suggestion nobody is working on after a while.
