### ISSUE TITLE
[Bug]: Late joining as a court mage makes you unable to use any of your spells

### ISSUE THREAD

**Issue by Tipy1802** [Darkrp-community/OpenKeep#344]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

I late joined as a court mage, old and had my hat on, and I could not cast any spells. They were red and unable to be used. No matter what I tried I couldn't get them to function. I imagine it has to do with the recent PR that changed court mage stuff, but this is an unintended effect

### How to reproduce

Late join as a court mage, unsure if you need to late join or does it always happen but that is how it was for me

**Comment by NPC1314** [comment]
Age and having hat has no bearing on ability to cast spells. Error is probably a missing mind check, PR 345 seems to solve it.
