### ISSUE TITLE
[Bug]: Court Mage spells on latejoin *STILL* do not work

### ISSUE THREAD

**Issue by GitGobbler** [Darkrp-community/OpenKeep#352]
### Checks

- [ ] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

Similar to #344, late-joined as Court Mage. Unlike before, the spells are no longer red and instead appear to be ready to be used, however attempting to select a spell for use does not work. Attempting to reload the game does not fix this issue, and instead reveals the spells to still be red upon reconnecting. Issue #344 was closed as PR #345 was believed to correct this, but this has not proven true.

### How to reproduce

Late-joining as Court Mage. 

### Round ID

Castle363-20.25.11

**Comment by NPC1314** [comment]
What combo of race, patron, age and flaw?

**Comment by GitGobbler** [comment]
> What combo of race, patron, age and flaw?

Human, Noc, Middle-Age, Alcoholic

**Comment by NPC1314** [comment]
Its the Noc part, the patron runtime creeping into every part of existence, joy.
Fix up.
