### ISSUE TITLE
[Bug]: Item UI bug

### ISSUE THREAD

**Issue by pvtSPEDwarrior** [Darkrp-community/OpenKeep#360]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

Out of nowhere in the middle of the keep items in my invetory UI began to rearrange themselves. Afterwords suddenly my saber was in my chest slot with my leather armor, then on my right hip over the quiver. It would randomly change spots and I couldn't select it no matter what even if the highlighted text said saber. 

### How to reproduce

I have no idea what could have caused it. Aside from seconds before it happened I had been holding a lit zig and it suddenly disappeared and went invisible in my hand.

### Round ID

Stone374-03.36.44

**Comment by ThePainkiller** [comment]
Cannot replicate this bug in any possible way, nor have been any other reports of it ever happening so far.
