### ISSUE TITLE
[Suggestion]: Make Alcohol Bottles Hold A Bit More Liquid ~24 oz Instead of 15 oz

### ISSUE THREAD

**Issue by Optimism333** [Darkrp-community/OpenKeep#365]
### Category

Balance

### What is the suggestion?

Simply make wine bottles hold a little more liquor, so you can pour 3 full mugs/goblets rather than barely fill 2.

As a small addendum to the suggestion: 
Bottles of different sizes? A smaller bottle (beer) holding 16 oz, and a larger one (wine) holding 24 oz.

### Why is this suggestion good?

A little more convenience for servants pulling wine up from the cellar. Two wine bottles would serve six guests at a feast, or eight if the amount poured was 6 oz per cup. It would allow serving more drinks to a depressed noble from a single bottle: 3 full goblets instead of barely 2.

More alcoholism.

Makes it easier to be the liquor.

### Staff consulted

N/A

**Comment by Mojamble** [comment]
The merchants guild supports this.

**Comment by cornercube** [comment]
quick and easy fix, I will get to it

**Comment by cornercube** [comment]
![image](https://github.com/user-attachments/assets/1e3c8013-e699-4797-9e7f-8ad63f22da95)

could start with a global 25 unit buff
small and magnum bottles would need to wait for their own sprites
