### ISSUE TITLE
[Bug]: Sleeping gives no triumphs

### ISSUE THREAD

**Issue by BadAtThisGame302** [Darkrp-community/OpenKeep#382]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

Slept during night, on a bed and as ruler Queen, got no triumphs.

![image](https://github.com/user-attachments/assets/d205c6c3-163f-4683-8a26-38826fbe0d4e)

### How to reproduce

Go to bed.
No Nights Survived: 1/2/3 etc pops up.
Wake up.

### Round ID

Crystal1419-22.59.59

**Comment by 1N7Slayer** [comment]
Villains gain no triumphs from sleeping, and the roundstart ruler is assigned villain status -- bizarrely.
