### ISSUE TITLE
[Bug]: Heart still beats after death

### ISSUE THREAD

**Issue by Piston1937** [Darkrp-community/OpenKeep#386]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

The sprite for the heart still beat even after death.  

### How to reproduce

Kill someone and remove the heart

**Comment by ThePainkiller** [comment]
Not a bug but a sprite issue lmao I thought this was about listening to someone's heartbeat while they were dead and it still beating.
