### ISSUE TITLE
[Bug]: Stab embedding no longer works properly

### ISSUE THREAD

**Issue by Piston1937** [Darkrp-community/OpenKeep#394]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown, DakkaTown

### Describe the issue

in my case I stab something with a scalpel and it says it embeds but I still have it in my hand.  it is in there body as embedded but hasn't left my hand, I can still stab them with it and cut however when I decaped with it in their head it left my hand and fell to the ground.

### How to reproduce

Stab someone till it embeds

**Comment by ThePainkiller** [comment]
Pretty sure the embedding is meant as flavor text for surgeries, meaning that hemostats and clamps are supposed to "stay" on the character currently undergoing surgery and have nothing to do with actual weapon embed code during combat

**Comment by Piston1937** [comment]
No…… before the medial update embedding a weapon would remove the weapon from your hand and give you the twist or take intents.  Twist would twist the embedded weapon and take would remove it without needing to look at the inspectz

**Comment by Piston1937** [comment]
Note this doesn’t only happen with scalpels.  It’s happened with normal daggers too.

**Comment by NPC1314** [comment]
since embed removed not a issue any more
