### ISSUE TITLE
[Bug]: Animal AI no longer eats corpses

### ISSUE THREAD

**Issue by Piston1937** [Darkrp-community/OpenKeep#425]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

Rous no longer butcher corpses.  Spawned a rous atop a corpse and it doesn't eat it.  Probably an AI problem

### How to reproduce

Spawn a rous, kill it then spawn another

**Comment by Piston1937** [comment]
Volfs still do it. But rous don't

**Comment by NPC1314** [comment]
fixed
