### ISSUE TITLE
[Bug]: Assassians don't show on the Admin Check Antag list.

### ISSUE THREAD

**Issue by Piston1937** [Darkrp-community/OpenKeep#426]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

There was an assassain antag in the round.  They were not in the antag list.  They should be.

### How to reproduce

Have someone spawn as assassain then open the admin Check Antags in the Gamemaster tab.

**Comment by BadAtThisGame302** [comment]
This PR, https://github.com/Darkrp-community/OpenKeep/pull/442, fixes this.
