### ISSUE TITLE
[Suggestion]: Assassain Rework

### ISSUE THREAD

**Issue by Piston1937** [Darkrp-community/OpenKeep#427]
### Category

Balance, Other

### What is the suggestion?

As of right now the Assassain isn't clear on what you are supposed to be doing and there are some things that could be made clearer.
1. Their spawn message should not include the words "LET THE BLOOD FLOW!" this is too easy to interpret as Go Frag. It should be more along the lines of "I Memorized my list of targets, Time to get to work."
2. Graggar should not be involved at all, again to avoid implying the blood for the blood god.
3. Make them an official antag.  Even if they aren't technicaly just make them mechanicaly an antag so we as moderators can see at a glance who's going to be causing problems and so they show up in the logs and at the end of the round as I killed these people.

### Why is this suggestion good?

To make the role clearer

**Comment by BadAtThisGame302** [comment]
> 2. Graggar should not be involved at all, again to avoid implying the blood for the blood god.

What God do you suggest, I was thinking Xylix? Or Matthios?

**Comment by Piston1937** [comment]
Xylix would be my go to. Or Ravox.  Or just let the players chosen patron stay.

**Comment by Piston1937** [comment]
Eoran Assassain, dendor Assassain, and so on.

**Comment by ThePainkiller** [comment]
Closing issue as Assassin has received at least two reworks over the course of its existance + flavor text changes and rebalances. If this becomes a persistent issue, please file another suggestion report.
