### ISSUE TITLE
[Suggestion]: Allow Skills To Be Selectable In Character Setup

### ISSUE THREAD

**Issue by lavillastrangiato** [Darkrp-community/OpenKeep#430]
### Category

Balance, Other

### What is the suggestion?

Pretty much the title. Add a tab or a pop-up that gives you a certain amount of "points" that you can put into any skill you like, maybe with a bonus depending on what class you pick, maybe with bonus points depending on your age. Perhaps some skills would be role-restricted or just limited in how much you could level them.

I wouldn't mind trying my hand at coding this it's just that I suck at coding and I'd rather feel out how much this is desired rather than waste my effort in learning.

### Why is this suggestion good?

I am certain there are some people who enjoy rolling for a list of pre-selected skills each round, and having the potential to get some really lame stats because of random chance. That's not sarcastic: some people enjoy the thrill of randomness and it allows them to vary their RP.

However, I find it incredibly annoying when I want to, say, build a drying rack as a maid or what-have-you for cooking purposes, or I want to stitch a dress or a bag or _something_, and I have to rely on random numbers to even do something as simple as set up some goddamn sticks to make some raisins. 

I think this would open more roleplay avenues to people who want their character to know how to do some random skill that they learned from their past, or just build their character differently. Obviously there are concerns of powergaming or whatever but that's why there would be limited skill points, so not everyone could take legendary combat.

**Comment by ThePainkiller** [comment]
Incredibly hard to balance, too snowflakey, and will be powergamed to oblivion. No.
