### ISSUE TITLE
[Suggestion]: Sending Mail off map (to the admins)

### ISSUE THREAD

**Issue by Piston1937** [Darkrp-community/OpenKeep#431]
### Category

Balance

### What is the suggestion?

Either through  the hermes or some messenger zard cage object important people should be able to address the admins as IC off map characters and send and receive letters.  Would allow for things like the merchant sending letters to the guild to complain about the kings tax (Maybe an embargo event could be added so the merchant isn't as easy to bully around).  Or the king sending to ask about local marriages for their children and give the admin a chance to spawn in a noble for a ghost or something.  Would help the players ask for admin aid without breaking charater or praying to the gods overly much.

### Why is this suggestion good?

Have the possibility to improve the IC events with admin help.

**Comment by ThePainkiller** [comment]
So basically, an Eriscode fax machine?

**Comment by NPC1314** [comment]
Hi, thanks for your suggestion! Unfortunately it's not feasible for us to prioritise this feature right now, but we'll keep it in mind and we'll hopefully revisit it in the future. To keep the issues page relevant we have to close suggestion nobody is working on after a while.
