### ISSUE TITLE
[Bug]: Keys cannot be sold in Peddlers

### ISSUE THREAD

**Issue by SaintBurgher** [Darkrp-community/OpenKeep#477]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

Keys (such as stall keys and inn keys) cannot be sold in the Peddler units.
![image](https://github.com/user-attachments/assets/5b8f16f9-b888-4c32-972b-aca92cdd4ac6)

### How to reproduce

Try to put a key into the Peddler.

**Comment by ThePainkiller** [comment]
Intended behavior, as keys are literally how you lock/unlock peddlers.
