### ISSUE TITLE
[Suggestion]: Defund the VL's night school; Stop letting every vampire convert pick a new class and double their skills.

### ISSUE THREAD

**Issue by Mojamble** [Darkrp-community/OpenKeep#492]
### Category

Balance

### What is the suggestion?

So, vampires are OP. Not a fun OP, a hellish OP. I don't think many people will argue it. People throw around reasons constantly - infinite stamina being the big one. But I don't think this is the issue as much as some people do.

I'd argue the biggest issue with vampires right now is how, when converted, you get to pick a class. See, this is an issue, because it adds on to your skills at a flat value.

If a warrior gets nabbed, consoomed, and picks warrior? Guess what, they've got legendary or master swordsmanship now, and they're going to use it to make you read Twilight like it or not.

Legendary swift daggers for rogues with the dodge perk. Let that sink in.

If the ability for in-round converted thralls to pick a class was axed, we'd see far less one sided fights - the VL still remains a power house, the starting thralls are still HIS NUMBER ONE GUYS, and more thought has to be put in to who you nab, because some random fisher won't suddenly become Ravox's number one fragger just because you forced your bloodplay kink on them. 

That's my take, anyways.

### Why is this suggestion good?

See above. My brain is huge. Also, I think I outlined it decent enough, maybe?

**Comment by NPC1314** [comment]
VL will get some attention as soon as the bandit phase is done, so pretty soon. This will be considered then

**Comment by BadAtThisGame302** [comment]
There is a PR up for test-merge that fixes this issue. Will close this issue once merged.
