### ISSUE TITLE
[Suggestion]: Limit Rare Combat Drifters To 2 Slots Per Round

### ISSUE THREAD

**Issue by Optimism333** [Darkrp-community/OpenKeep#554]
### Category

Balance

### What is the suggestion?

Rare combat drifters: the ones with skill level (4) or above in a combat skill and/or strong armor should be limited to 2 slots per round.

There's now **seven** of these rare race-locked and single-slot drifter roles that I can list off the top of my head:
Bladesinger (Elf), Longbeard (Dwarf), Lancer (Humen), Swordmaster (Humen), Immortal Bulwark (Aasimar), Vaquero (Tiefling), Sentinel (Elf)

Having the chance for ALL of these to appear in a round if they're rolled or the triumph toll is paid seems a bit much, especially if I push the change to pq to make it increase the chance of these roles being rolled (thus bypassing the triumph cost).

Therefore I suggest that these rare drifters with combat skills of skill level (4) and above, in addition to strong stats and armor, be limited to **2 per round** (same slot number as royal guards).

### Why is this suggestion good?

Too many rare drifter roles make the term "rare" redundant. Many of these roles are royal guard tier or above, so it seems reasonable to subject them to a slot limit similar to royal guards to prevent rounds from being flooded with powerhouse drifters.

Vaquero is a bit of a grey area on the list, because unlike all the other roles it doesn't get plate armor, but I left it on regardless since it has expert (4) combat skill in swords, and will get a buff if #553 is merged.

**Comment by Catalaria** [comment]
What about being limited to four?
Four sounds like a pretty justified amount

**Comment by NPC1314** [comment]
Hi, thanks for your suggestion! Unfortunately it's not feasible for us to prioritise this feature right now, but we'll keep it in mind and we'll hopefully revisit it in the future. To keep the issues page relevant we have to close suggestion nobody is working on after a while.
