### ISSUE TITLE
[Bug]: Class selection window white and featureless for adventurer

### ISSUE THREAD

**Issue by hollyhocc** [Darkrp-community/OpenKeep#565]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

When latejoining as an adventurer and clicking on the class select button, the window shows up as pure white.
This has happened multiple times for me, though once yesterday (the 22nd) it randomly worked and went from white to the correct UI. I have no clue what I did to make it work, unfortunately.

### How to reproduce

Join as adventurer
Click the select button face thing
Stare
Relog
Try again
Cry so much :(

### Round ID

Jewel683-16.43.24

**Comment by hollyhocc** [comment]
i hate byond

**Comment by hollyhocc** [comment]
attempted:
downgrading BYOND versions
clearing BYOND cache
clearing michaelsoft edge cache
restarting pc computer
being sent to main menu and rejoining adventurer queue
none worked

**Comment by NPC1314** [comment]
The adventurer code is a terrible thing but this sounds more like something TGUI clientside. I imagine an overhaul of migration code could help but thats not in the cards in the foreseeable future.
Can't replicate, no other reports of this occuring, closing issue for now.
