### ISSUE TITLE
[Bug]: WIZARD SPELLS OH GOD

### ISSUE THREAD

**Issue by Mojamble** [Darkrp-community/OpenKeep#572]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

The wizard has two charges of fus-ro-dah and lesser fireball atm. Help.

### How to reproduce

Play wizard. Frag.

### Round ID

huh

### Staff ckey

wuh

**Comment by sanshoom** [comment]
That's not a bug. That's intended.

**Comment by NPC1314** [comment]
https://github.com/Darkrp-community/OpenKeep/pull/573  done
