### ISSUE TITLE
[Suggestion]: Make Wicker Baskets and Oak chests craftable

### ISSUE THREAD

**Issue by AudiGzz** [Darkrp-community/OpenKeep#606]
### Category

Other

### What is the suggestion?

Basically the option to make wicker baskets and oak chests craftable as they fit the setting more to be in the hands of towners. Mainly just flavor thing really. Should be able to still make them under carpentry with the same craftdiff as the current chests. As well as crafting recipes for the wicker basket can be 5-6 sticks or whatever, and the oak chests just use the regular one log. 

### Why is this suggestion good?

More snowflake variety is good I suppose for items like this.

**Comment by NPC1314** [comment]
one step ahead of ya, its in testmerge
