### ISSUE TITLE
[Bug]: Inverted visor helmet bug

### ISSUE THREAD

**Issue by BadAtThisGame302** [Darkrp-community/OpenKeep#607]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown, DakkaTown

### Describe the issue

You are unknown when the visor is open, you are named when the visor is shut.

### How to reproduce

Right click any visored helm.

### Round ID

Tapir733-18.10.39

**Comment by NPC1314** [comment]
Caused by changes made to helmets in https://github.com/Darkrp-community/OpenKeep/pull/526 or a PR close to it in time.

**Comment by NPC1314** [comment]
Considering just nuking on hip slots for helmets so we can just use not complicated procs that causes more issues.

**Comment by NPC1314** [comment]
#743 should fix this

**Comment by ThePainkiller** [comment]
Closed as completed by #743 .
