### ISSUE TITLE
[Bug]: Weaponsmith can't spawn roundstart and the slot is gone

### ISSUE THREAD

**Issue by ThePainkiller** [Darkrp-community/OpenKeep#636]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

Readying as Weaponsmith doesn't spawn you, whether there's an armorer or not readied.

### How to reproduce

1. Ready as weaponsmith
2. Round starts
3. Get "I couldn't find a job to be.." message

### Round ID

Tapir774-06.04.57

**Comment by NPC1314** [comment]
maybe its just dunmanor mapping error, lacking spawn point or smth

**Comment by ThePainkiller** [comment]
Still an issue, and it still is an issue even localtesting on old roguetown map.

**Comment by NPC1314** [comment]
remember seeing a runtime with weaponsmith spawn location somewhere, giving it a try to make a fresh spawner on the map, tho shouldnt affect slot
