### ISSUE TITLE
[Bug]: Decorated helmets do not cover half of your vision

### ISSUE THREAD

**Issue by BadAtThisGame302** [Darkrp-community/OpenKeep#670]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown, DakkaTown

### Describe the issue

It is a great bucket helm, it should cover half of your vision

### How to reproduce

Make a decorated helmet and wear it

### Round ID

Tower807-17.47.30

**Comment by ThePainkiller** [comment]
Correct. This PR got merged before revision was tackled about how they are literally just "hounskull/greathelm/knight helmet with decoration on top but not visored and with higher visibility". Sigh.

**Comment by BadAtThisGame302** [comment]
This fixed it.
https://github.com/Darkrp-community/OpenKeep/pull/683
