### ISSUE TITLE
[Bug]: Multiple messed up hairs

### ISSUE THREAD

**Issue by BadAtThisGame302** [Darkrp-community/OpenKeep#671]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown, DakkaTown

### Describe the issue

Equip one of these below:
Adventurer (it is flying over the head)
Berserker (is bald)
Nobility (is bald)

### How to reproduce

Equip one of the above hairs and see results.

**Comment by BadAtThisGame302** [comment]
> I can confirm nobility being bald, but Berserker and Adventurer worked fine for me

Adventurer: 
![image](https://github.com/user-attachments/assets/fdb751ab-21d7-4b5c-8a13-ee09645820fa)

Berserker:
![image](https://github.com/user-attachments/assets/d2d6a072-a8ca-4232-9ca9-5c806d46a892)

**Comment by ThePainkiller** [comment]
Adventurer has floating pixels, but what's wrong with Berserker? Use a darker hair tone and you'll see it's like a balding haircut, this has always been thus

**Comment by NPC1314** [comment]
I'll take a look, should be easy to sort

**Comment by NPC1314** [comment]
Berserker is same as always been, adventurer had a 1 pixel offset, and nobility had a icon name mismatch. Was that really all? Fixed anyways.
