### ISSUE TITLE
[Bug]: Crossbow and Ammo Smithing borked

### ISSUE THREAD

**Issue by NormalAnomaly** [Darkrp-community/OpenKeep#701]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

Even the drifter master smith with all legendary smithing skills cannot reliably make ammo or crossbows.  Its as though they are not correctly tied to a smithing skill so he is left smithing like he has zero skill.  In the limited testing I did, I got no level-up in some new skill either to suggest this is intentional.

### How to reproduce

Smith a crossbow/arrows with a trained smith.  Notice a lot of failed strikes in spite of having high smithing skills.  Probably spoil the bar before finishing your project.

**Comment by lavillastrangiato** [comment]
From a quick glance at the code, it seems like the Engineering skill is required to craft bolts and crossbows on an anvil. Drifter smiths and weaponsmiths have the skill, but it's not very high. This probably causes you to fuck up the strikes.

It kind of makes sense to me that maybe the town smiths wouldn't be as effective at making the crossbows, as they're more powerful than bows, but I don't see why a legendary blacksmith wouldn't have a stronger engineering skill... then again, it means less people would play towner roles, which is ideally avoided.

**Comment by ThePainkiller** [comment]
Correct, I've made crossbow an engineering recipe, you can ask a mason to make you one since they start with high engineering. I wanted to make Masons more useful by giving them engineering and just give minimal engineering to smiths just to not be useless, but since leveling anything on an anvil has been made overly difficult (for good reason), I might have to bump their engineering skills so that it's not outright impossible for smiths to make even cogs.

**Comment by NormalAnomaly** [comment]
Just throwing out what I remember from when pyro/poison bolts were added, that is when engineering skill was added to the smiths because the special bolts needed it and it was for whatever reason considered preferable to give smiths engineering than to make it weaponsmithing or something else.  Given the weaponsmith is already basically unplayed compared to armorsmith, it'd be entirely fine for this to be shunted back to weaponsmithing.  Smiths having engineering was the lazy path anyway, which at least at one time took actual engineering work away from the masons.

I get the logic for engineering on the crossbow even if I think weaponsmithing is the more natural and gameplay appropriate direction, but I'd have never guessed that bolts and arrows would need the skill primarily concerned with constructing mechanical gates and trapdoors.

**Comment by ThePainkiller** [comment]
That's a fair compromise, we can make the bolts take weaponsmithing instead, but since crossbows will have a modifier for damage, they'll have to remain on engineering to avoid getting them easily masterwork

**Comment by NormalAnomaly** [comment]
Just cause that seemed a bit odd, I did some testing.  A normal mason can just as easily mass produce flawless-masterworkd crossbows and bolts.
