### ISSUE TITLE
[Bug]: Able to latejoin as different patron as certain roles.

### ISSUE THREAD

**Issue by AudiGzz** [Darkrp-community/OpenKeep#724]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown, DakkaTown

### Describe the issue

Ok so basically court magician and priest, cant think of any others. That I believe force you to have Astrata for priest or Noc for court mage currently at roundstart. Obviously don't let you ready up as it, but yet all you have to do currently is just latejoin and you'll be fine to choose whatever patron you want. Only making this issue cause people have complained and never made a issue on github. 
https://cdn.discordapp.com/attachments/898376327097364573/1284658012501442580/image.png?ex=66e76e81&is=66e61d01&hm=a22f4727005bd70e702c63b9cd31b715081e714a314320ff7b2b2b6c766827eb&

https://cdn.discordapp.com/attachments/898376327097364573/1284658065714581555/image.png?ex=66e76e8e&is=66e61d0e&hm=8939d37a184ded69ca9e01bc97f6a33a85ba4b23d50e49a25b7149bb79228474&

### How to reproduce

Change your patron to pestra or w.e god that will not let you ready up as priest or court magician. Don't get the role > You're still able to late join with the selected patron.

### Round ID

Been happening for a while. But Sherwood890-23.08.50

**Comment by NPC1314** [comment]
Wow so this is a issue huh?
Well, fixed priest, if anyone want to fix the court whozard they can apply the same method, personally Im not sure Noc wants em.
