### ISSUE TITLE
[Bug]: Female dwarf Grenzel mercs don't spawn with their outfit correctly.

### ISSUE THREAD

**Issue by 1N7Slayer** [Darkrp-community/OpenKeep#725]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

As the title states, they did not show up with sprites for their outfit upon spawning in.

**Comment by ThePainkiller** [comment]
Any screenshots of what they DO spawn with? It may have to do with not having female sprites for their gear.

**Comment by 1N7Slayer** [comment]
![image](https://github.com/user-attachments/assets/875096ef-6633-4393-838b-022b503a836d)
Shirt, cuirass, pants, boots all do not spawn.

**Comment by ThePainkiller** [comment]
Unfortunately this is because they do not have sprites, because they weren't intended for female dwarves it seems
If there is a female sprite on code it is because the elves use those for their clothing, but there is no fem dwarf variant on code whatsoever
