### ISSUE TITLE
[Bug]: net effect does not wear off on removal, cannot be mitigated by catching them

### ISSUE THREAD

**Issue by Cre77** [Darkrp-community/OpenKeep#726]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

title. While messing around on a testing server, I noticed that the net debuff does not get removed on removing the actual net from yourself - it only elapses after the three minutes of the actual debuff.

You can also "catch" a net, but since it has a pickup delay like with catching any other object, you will get ensnared first, receive the debuff, then the net will magically unsnare you and move itself into your hand - debuff still persisting. Abysmal.
You also instantly remove the net on resisting, not sure if that's intended either.

### How to reproduce

Get net thrown at you. Catch it, let it happen - it doesn't matter. You can test this either by spawning in two characters, or by looking up and throwing the net upwards at a tile over yourself. QUICK, GUARD MAINS - ABUSE IT BEFORE IT'S NERFED

**Comment by ThePainkiller** [comment]
I'll tackle it on my next qol fixing PR
