### ISSUE TITLE
[Bug]: Weiner and onions has no sprite

### ISSUE THREAD

**Issue by BadAtThisGame302** [Darkrp-community/OpenKeep#748]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown, DakkaTown

### Describe the issue

Title.

### How to reproduce

Make a weiner and onions, see nothing.

### Round ID

Frogge920-01.28.36

**Comment by NPC1314** [comment]
I straight up forgot to make those sprites, they never existed, dont have anything to to with the farming stuff, tho I added the sprites to that PR so now it kinda does.
