### ISSUE TITLE
[Bug]: elf bladesinger armor gloves disappearing on sprite if side-ways

### ISSUE THREAD

**Issue by messagecypher** [Darkrp-community/OpenKeep#749]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

when you spawn in as an elf bladesinger and wear the brown wood-like armor, the gloves disappear when viewed from the side despite being present when facing forwards and backwards.

### How to reproduce

spawn in as a bladesinger elf with the brown armor sprites, turn to the side

**Comment by ThePainkiller** [comment]
Male? Female?

**Comment by NPC1314** [comment]
/obj/item/clothing/suit/roguetown/armor/rare
	sleeved = 'icons/roguetown/topadd/takyon/onmob_racial.dmi'
	sleevetype = null

Bladesinger is child of that obj, prob just needs a sleevetype set and sprite added to that icon file
