### ISSUE TITLE
[Bug]: ZAMN SHIRT SLOT ARMOR DONT WORK NO MORE!!!

### ISSUE THREAD

**Issue by 0nemore** [Darkrp-community/OpenKeep#756]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

Armor on the shirt slot no longer works, examples are the gambeson variants and the chainmail variants, they work on armor slot but no longer on shirt slot and that's kinda doodoo

### How to reproduce

Put armor on shirt slot. Hit yourself. Weep. :(

**Comment by NPC1314** [comment]
Fix already in the pipeline
