### ISSUE TITLE
[Bug]: help im drownin and got shocked. can i pick class? pls?

### ISSUE THREAD

**Issue by AudiGzz** [Darkrp-community/OpenKeep#764]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

Basically, when u drift you have a chance to spawn in the literal river, or kneestingers. I understand blah blah blah make the murderwoods murder again and dangerous. But being fucked over upon literally spawning in cause of some bug that spawns you in the river before you even pick a class is ass.

### How to reproduce

drift, some spawns will spawn ontop of kneestingers or spawn u in a river. congrats bug reproduced.

### Round ID

been happening for a while

**Comment by ThePainkiller** [comment]
I can confirm I've been the victim of spawning on top of kneestingers as well. It's terrible.

**Comment by NPC1314** [comment]
Very funny but not the intent tho, might been fixed in the latest patch, we'll keep an eye
