### ISSUE TITLE
[Bug]: Crainum-tearing now Instakills for some reason.

### ISSUE THREAD

**Issue by Cre77** [Darkrp-community/OpenKeep#777]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

Tearing someone's cranium with a blunt or stabbing weapon now makes them instadie. Previously it only paralyzed you.
I really have no idea what causes this, since it had the "mortal" flag to instakill crit-weak enemies even before the changes I made. 

### How to reproduce

1. stab/hit someone in the top of the skull area
2. they're dead!
Had this happen both when blunt-whipping someone I was trying to apprehend, and stabbing them in the head as an assassin.

**Comment by ThePainkiller** [comment]
Closing as completed by #791 .
