### ISSUE TITLE
[Bug]: Hermailers are Broken Again, but Differently

### ISSUE THREAD

**Issue by NormalAnomaly** [Darkrp-community/OpenKeep#782]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

Name-addressed letters and packages are not able to be picked up by their target.  They get shunted to the master of mails in the steward's office correctly at least.  No idea if coin-operation letters go to the master of mails, didn't think to test that at the time.

I also noticed the "You have a letter from Name Here" text was different between the coin-operation letters and paper-clicked-on-hermailer letters.  The coin-ops was a light blue/grey if I remember right, and the other was a different font size and the same light yellow as some other informational text in the chat window.  

### How to reproduce

The fast and easy way.  

Get paper, apply to hermailer, send to your name, get the confirmation text that you now have a letter waiting for you, attempt to get the letter from the mailer.

For the sake of completeness it should be tested with a package too, same as above.

Also feed mailer a zenny, right click to send a coin-operation letter, send to yourself and observe as above.

**Comment by NPC1314** [comment]
Two possible causes
https://github.com/Darkrp-community/OpenKeep/pull/641 and related follow up PRs
or
https://github.com/Darkrp-community/OpenKeep/pull/678
