### ISSUE TITLE
[Bug]: Arrow overlay not properly fixed for longbow

### ISSUE THREAD

**Issue by ThePainkiller** [Darkrp-community/OpenKeep#802]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

![image](https://github.com/user-attachments/assets/5a520653-4c59-42b9-bbc3-64a8dc31b218)

### How to reproduce

1. Grab longbow
2. Knock an arrow on it
3. Get the arrow too offset to the bottom left of the screen

**Comment by ThePainkiller** [comment]
Fixing it myself on a future PR, but there's still the issue of the arrow sprite on the mob sprite.

**Comment by NPC1314** [comment]
this issue is fixed
