### ISSUE TITLE
[Bug]: spawned in as a drifter and the only combat class was bandit

### ISSUE THREAD

**Issue by sanshoom** [Darkrp-community/OpenKeep#810]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown

### Describe the issue

Spawned in as a Drifter, and the only combat class that appeared was bandit. Even switching to pilgrim and back to combat didn't help.
<img width="190" alt="image" src="https://github.com/user-attachments/assets/e879a4d7-fae1-4500-90f6-ce8b6b4261e9">

### How to reproduce

>spawn in as drifter

### Round ID

Shroom1004-00.58.37

**Comment by BadAtThisGame302** [comment]
Coded it specifically for your ckey because I hate you.
