### ISSUE TITLE
[Suggestion]: Importing Instrument Midi's

### ISSUE THREAD

**Issue by Verin-Verdelet** [Darkrp-community/OpenKeep#820]
### Category

Other

### What is the suggestion?

Allow me and all the other intrument/bard players to be able to bring in our own custom music so we can jam it out as unique, individual artists.

### Why is this suggestion good?

Because the drum has like 3-4 songs, the guitar 5-6, mandolin and flute the same, and harp like 3-4 and it's very stale and gets old very fast. Every server, even the serious ones i've played on has allowed custom music, and just slaps the balls of the people who abuse it to take people out of immersion.
We would have more colorful bards and likely more people would feel like using the instruments if it was not the same thing you've heard 500 times before.

**Comment by ThePainkiller** [comment]
There is NO way this isn't going to be abused to play non-period appropiate music and overall memery :)

**Comment by Optimism333** [comment]
Rather than close this idea and dismiss it outright, perhaps we could open a middle-ground suggestion/conversation to add more music options for instruments?

**Comment by ThePainkiller** [comment]
Adding more music options was not the scope of this suggestion, it was to add midi support to make one's own music. If they want to do that, they can do so on another suggestion post.

**Comment by Verin-Verdelet** [comment]
I just want to say, it's kinda fucked up people say "WELL PEOPLE WOULD PLAY NOT period appropriate" then someone picks up the dwarven boombox which takes midis and starts blaring "Gangsters paradise" real cool, real mature, really takes me into that YE olde feeling.

**Comment by ThePainkiller** [comment]
> I just want to say, it's kinda fucked up people say "WELL PEOPLE WOULD PLAY NOT period appropriate" then someone picks up the dwarven boombox which takes midis and starts blaring "Gangsters paradise" real cool, real mature, really takes me into that YE olde feeling.

Yeah that's another feature that has to go in all honesty. Midis do still fucking suck.

**Comment by Verin-Verdelet** [comment]
Look as long as it's CONSISTENT i don't really care. I was willing to just accept the L on midi's till i got into round and heard BEEN SPENDING MOST OUR LIVES LIVIN' IN A GANGSTER PARADIIIIIIIISE.
Which, no one seemed to notice but me or care about, and when i tried to change it to something more period specific, IE: A mount and blade song, i was chastised by the players around me.
Perhaps an announcement reminding people not to do it or a rule should be put into affect? As it stands the community at large and you do not seem to be in agreeance.

**Comment by Verin-Verdelet** [comment]
Also i will say song....5? Of the Mandolin is castle crashers music which was made in 2008 and uses modern music conventions and immediately takes me out of the game because it's not ye olde music, it's modern music for a semi-dated game using modern music style choices. 
So if we really want to be "period appropriate" we should AXE fucking video game music not made to actively reflect the music of the time. Not newgrounds horseshit.

**Comment by ThePainkiller** [comment]
> I was willing to just accept the L on midi's till i got into round and heard BEEN SPENDING MOST OUR LIVES LIVIN' IN A GANGSTER PARADIIIIIIIISE. Which, no one seemed to notice but me or care about, and when i tried to change it to something more period specific, IE: A mount and blade song, i was chastised by the players around me. 

This should've been reported as LRP and it's something our moderation team is taking steps into preventing, if you checked the announcements channel on the Discord server you should see that we are trying to enforce tighter HRP enforcement policies to avoid people treating this like just "tgstation but medieval setting" and avoid meme fuckery like this. All the parties involved were at fault if they think it's better to play meme music than keeping things period appropiate.

> Also i will say song....5? Of the Mandolin is castle crashers music which was made in 2008 and uses modern music conventions and immediately takes me out of the game because it's not ye olde music, it's modern music for a semi-dated game using modern music style choices.

You were raising solid arguments and now throw this which I can only interpret as a salt comment done in bad faith. Yes I'm aware we have Stalker guitar songs, the Malagueña, and Asturias which are literally modern music, but are at least vague enough melodies that fit either thematically (with the heavy spaniard influence for Tieflings, or the bleakness of the setting itself for stalker guitar songs). Don't be like this.

**Comment by Verin-Verdelet** [comment]
I did not mean it to come off as salty, it's just frustrating and i feel comes off as very limiting for bards to come up with fun gimmicks with songs that have vague melodies like you said before. It's just really vague what counts as "period specific" in a fantasy setting where we even have an item that's a "Boombox" or our techno-magic horseshit in the banks and the scom. What is period specific in a setting where we have elements of scifi AND magic, And feudalism
