### ISSUE TITLE
[Bug]: Bucket doesn't allow washing

### ISSUE THREAD

**Issue by TheMrBakit** [Darkrp-community/OpenKeep#829]
### Checks

- [x] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

Dun Manor

### Describe the issue

The issue is the Bucket you buy from the Goldface(merchant Machine), doesn't allow you to use the water to clean the floor

### How to reproduce

1. Buy a bucket from the goldface 
2. Fill the bucket with water
3. Try to use the cloth on the bucket <-- doesn't work

**Comment by ThePainkiller** [comment]
Easy fix, thank you
