### ISSUE TITLE
[Bug]: Saiga Moving Faster Than They Should When Mounted

### ISSUE THREAD

**Issue by Optimism333** [Darkrp-community/OpenKeep#832]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

Dun Manor

### Describe the issue

According to several players in the Discord, and Onemore, saiga riders are moving far too quickly.

### How to reproduce

Ride a saiga.

### Round ID

N/A

### Staff ckey

N/A

**Comment by AudiGzz** [comment]
Same thing with uhh... le truffle pig don't know if its related, I haven't tried riding a bull either to see if it affects them as well. I have a video but its too big for github. https://discord.com/channels/1169125844246069298/1246144322039189555/1289162283749998592 Link to the video here.

**Comment by NPC1314** [comment]
should be fixed next round, goodbye zoomies
