### ISSUE TITLE
[Suggestion]: Have the ability to play as a male consort to a female ruler

### ISSUE THREAD

**Issue by BadAtThisGame302** [Darkrp-community/OpenKeep#836]
### Category

New Role

### What is the suggestion?

Basically codes some sort of system to allow women to be rulers while also allowing men to be their consorts, seeing as they are forced to either be solo rulers or consorts to a King.

### Why is this suggestion good?

It does not make sense the King could have a Queen but the Queen can't have a King.

**Comment by Cre77** [comment]
shameless stella pr 👎👎👎👎👎👎👎👎

**Comment by AudiGzz** [comment]
I just want to be one who cooks and cleans for her in the manor and be a loving father to our kids.

**Comment by ThePainkiller** [comment]
Rotwood is right around the corner.

**Comment by NPC1314** [comment]
Hi, thanks for your suggestion! Unfortunately it's not feasible for us to prioritise this feature right now, but we'll keep it in mind and we'll hopefully revisit it in the future. To keep the issues page relevant we have to close suggestion nobody is working on after a while.
