### ISSUE TITLE
[Bug]: Poison arrows don't really do much

### ISSUE THREAD

**Issue by AudiGzz** [Darkrp-community/OpenKeep#845]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

Dun Manor

### Describe the issue

ok so basically poison arrows are soft of useless. I shot a person with 1 poison arrow then normal one round they told me they weren't poisoned at all. I did not load out of the quiver directly, I pulled the poisoned arrow out of a satchel and loaded it and hit my target and it did nothing at all to them except just the regular damage, no poison or anything atleast from what I was told.

### How to reproduce

idk craft poison arrow and shoot someone with it. other people have been saying similar things about poison arrows as well.

**Comment by NPC1314** [comment]
If its a dwarf they got poison resistance but alchemy changed the poisons and we're trying to tweak them to a good state, tickrate on the server might be playing tricks as well. Offline one arrow with weak poison should take almost half the HP.

Anyways, its noted and we'll tweak the numbers a little to make the poison have more oompf

**Comment by AudiGzz** [comment]
Yeah decided to look into the code and saw that poison arrows can as well now use potent poison so I guess its understandable as poison arrows used to be a bit broken or whatever.
