### ISSUE TITLE
[Bug]: dye bins can't be broken, dragged,pushed.

### ISSUE THREAD

**Issue by AudiGzz** [Darkrp-community/OpenKeep#846]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

Dun Manor

### Describe the issue

ok you cant shove, push or pull a dye bin the menu pops up.

### How to reproduce

ok so craft dye bin, try to push or pull and you cant bug reproduced

**Comment by NPC1314** [comment]
breaking them can be done by just going combat mode though, same for a lot of structures and items

**Comment by AudiGzz** [comment]
Just posting this from discord so it won't get lost. yes I was in combat mode and the dye bin still didn't delete when I kept chopping it with my hunting knife, eventually it deleted but this was after I sort of gave up trying to break it. Idk if it was deleted by staff or not.
