### ISSUE TITLE
[Bug]: Standing in bad water poisons you

### ISSUE THREAD

**Issue by SaintBurgher** [Darkrp-community/OpenKeep#871]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

Dun Manor

### Describe the issue

Crawled down into the moat, never fell over, always standing. I got poisoned by this and started throwing up.

### How to reproduce

Stand in bad water.

### Round ID

Volf1079-01.42.09

**Comment by ThePainkiller** [comment]
We're aware of this issue and will most likely be solved when #866 gets merged, as standing on pools of reagents will no longer force you transfer these reagents unto you.
