### ISSUE TITLE
[Bug]: Fruit beer bottle bug.

### ISSUE THREAD

**Issue by AtomicGalaxy** [Darkrp-community/OpenKeep#924]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

Dun Manor

### Describe the issue

Sour fruit jackberry beer bottles will turn into normal bottles if you take the cork out and put it back in.

![image](https://github.com/user-attachments/assets/4846a7ab-ba6f-43d3-be2e-6f8b84bfefe3)

![image](https://github.com/user-attachments/assets/ffa38981-e8f0-4877-baca-9f14522944ca)

### How to reproduce

Take a jackberry sour beer bottle, take the cork out. and put it back in. Then examine the bottle and it'll be a normal one. 

It would be nice if it stayed since then you could have it on a shelf as "luxury" wine.

### Round ID

Gem1128

### Staff ckey

N/A

**Comment by BadAtThisGame302** [comment]
This happens with every single bottle you open. It loses the description because it technically is not the original.1
