### ISSUE TITLE
[Bug]: Vampire Lord Issues

### ISSUE THREAD

**Issue by anything86** [Darkrp-community/OpenKeep#927]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

Dun Manor

### Describe the issue

Vampire Lord still dusts instantly at dawn. Also can't regenerate lost limbs.
Could use either a longer timer, or some warning that dawn is coming, or both.

### How to reproduce

Be a vampire lord, try having a conversation outside at night.

**Comment by ThePainkiller** [comment]
When you say they can't regenerate lost limbs, have you tried sleeping into a coffin?

"Instadusting" will be fixed on a PR coming soon to you :tm:
