### ISSUE TITLE
[Bug]: Steward Treasury Logs are Broken

### ISSUE THREAD

**Issue by SaintBurgher** [Darkrp-community/OpenKeep#981]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

Dun Manor

### Describe the issue

Being fined and being paid does not log your name correctly. The name variable is showing as "treasury".
![image](https://github.com/user-attachments/assets/d2ea8da7-6e9d-4304-915d-b7930a50ab43)

### How to reproduce

Fine or pay someone using the machine then look in logs.

**Comment by NPC1314** [comment]
Not quite what I intended but whatever. The link to 962 to keep track of this bug, isnt solved.
